# Generated by Django 3.2.16 on 2022-12-19 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_city', models.CharField(max_length=200)),
                ('delivery_phone', models.CharField(max_length=200)),
                ('payment_created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
